[package]
name = "geobacter-rustc-driver-base"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
edition = "2018"

[dependencies]
geobacter-shared-defs = "1.0.0"
geobacter-rustc-help = "1.0.0"
