[package]
name = "geobacter-vk-core"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
edition = "2018"

[dependencies]
vulkano = "0.11.1"
geobacter-core = { path = "../geobacter-core" }
geobacter-shared-defs = { path = "../shared-defs" }
