[package]
name = "ir-gen"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]

[dependencies]
quote = "0.3.15"

[dependencies.syn]
version = "0.11.10"
default-features = false
features = ["full", "printing"]

[lib]
plugin = true