[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "mut-slice-ub"
version = "0.1.0"

[dependencies]
env_logger = "0.6"
log = "0.4.7"

geobacter-core = { path = "../../../geobacter-core" }
geobacter-runtime-core = { path = "../../../runtime-core" }
geobacter-runtime-amd = { path = "../../../runtime-amd" }
geobacter-amdgpu-std = { path = "../../../amdgpu-std" }
hsa-rt = { path = "../../../hsa-rt" }
