
[workspace]
members = ["hsa-core-gen", "hsa-core", "runtime",
           "ir", "ir-gen", "kernel", "rustc-plugin",

           "hsa-rt-sys", "hsa-rt",
           "tools/hsa-agent-info",

           "indexvec", "recycled-arc-vec",

           "examples/trivial", "examples/ndarray"]
