
[workspace]
members = ["hsa-core-gen", "hsa-core",
           "runtime-core", "shared-defs",

           "rustc-intrinsics", "bootstrap-rustc-driver",
           "rustc-driver", "rust-builder",

           "shared-intrinsics/common", "shared-intrinsics/vk",
           "shared-intrinsics/amdgpu",
           # TODO
           # "shared-intrinsics/nv",

           "legionella-vk-core", "legionella-vk-std", "runtime-vk",
           "examples/vk/trivial", "examples/vk/fractal",

           "amd-comgr-sys", "amd-comgr",
           "hsa-rt-sys", "hsa-rt",
           "tools/hsa-agent-info",
           "legionella-amdgpu-std", "runtime-amd",
           "examples/amdgpu/trivial", "examples/amdgpu/fractal",
           "examples/amdgpu/mut-slice-ub",

           "runtime-nv",

           # Tests here
           "tests/driver/run-pass/generic-substs"
           ]

[profile.release]
debug = true
debug-assertions = true
rpath = true

[profile.dev]
rpath = true
[profile.test]
rpath = true
[profile.bench]
rpath = true
