
[workspace]
members = ["hsa-core-gen", "hsa-core", "legionella-std",
           "runtime",
           "rustc-intrinsics", "legionella-intrinsics",
           "bootstrap-rustc-driver", "rustc-driver",

           "hsa-rt-sys", "hsa-rt",
           "tools/hsa-agent-info",

           "examples/trivial", "examples/ndarray",
           "examples/mat-mat-mul", "examples/fwd-conv", ]

[profile.release]
debug = true
debug-assertions = true
rpath = true

[profile.dev]
rpath = true
[profile.test]
rpath = true
[profile.bench]
rpath = true
