
[workspace]
members = ["hsa-core-gen", "hsa-core", "runtime",
           "ir", "ir-gen", "kernel", "rustc-driver",

           "hsa-rt-sys", "hsa-rt",
           "tools/hsa-agent-info",

           "indexvec", "recycled-arc-vec",

           "examples/trivial", "examples/ndarray",
           "examples/mat_mat_mul", ]

[profile.release]
debug = true
debug-assertions = true
rpath = true

[profile.dev]
rpath = true
[profile.test]
rpath = true
[profile.bench]
rpath = true
