[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "runtime"
version = "0.1.0"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.5"

[dependencies.hsa-core]
path = "../hsa-core"

[dependencies.hsa-rt]
path = "../hsa-rt"

[dependencies.hsa-rt-sys]
path = "../hsa-rt-sys"

[dependencies.indexvec]
path = "../indexvec"

[dependencies.ir]
path = "../ir"

[dependencies.kernel]
optional = false
path = "../kernel"
