[package]
name = "gemm"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gpgpu-gemm-example"
path = "main.rs"

[dependencies]
hsa-rt = "0.1.0"
gstd-amd = { version = "1.0.0", package = "geobacter-amd-std" }
grt-core = { version = "1.0.0", package = "geobacter-runtime-core" }
grt-amd  = { version = "1.0.0", package = "geobacter-runtime-amd" }
nd = { package = "ndarray", version = "0.13.0", features = ["approx"] }
env_logger = "0.6.2"
approx = "0.3.2"
nix = "0.17.0"
rand = { version = "0.7.3", features = ["small_rng"] }
