[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
name = "trivial"
version = "0.1.0"

[dependencies]
geobacter-runtime-core = { path = "../../../runtime-core" }
geobacter-vk-std = { path = "../../../vk-std" }
vulkano = "0.16.0"
env_logger = "0.6.0"
log = "0.4.7"
