[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
name = "examples-vk-trivial"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "examples-vk-trivial"
path = "main.rs"

[dependencies]
grt-core = { version = "1.0.0", package = "geobacter-runtime-core" }
grt-vk   = { version = "0.1.0", package = "geobacter-runtime-vk" }
vk = { version = "0.19.0", package = "vulkano" }
env_logger = "0.6.0"
log = "0.4.7"
any_key = "0.1.1"
