[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
name = "legionella-vk-std"
version = "0.1.0"

[dependencies]
log = "0.4.7"
legionella-vk-core = { path = "../legionella-vk-core" }
vulkano = "0.11.1"

[dependencies.hsa-core]
path = "../hsa-core"
