[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "legionella-std"
version = "0.1.0"

[dependencies]
ndarray = "0.10.12"

[dependencies.hsa-rt]
path = "../hsa-rt"

[dependencies.hsa-core]
path = "../hsa-core"
