[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "runtime-vk"
version = "0.1.0"

[dependencies]
vulkano = "*"

[dependencies.runtime-core]
path = "../runtime-core"
