[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "hsa-rt"
version = "0.1.0"
license = "MIT / Apache-2.0"

[dependencies]
serde = "1.0.19"
serde_derive = "1.0.19"
ndarray = "0.12.1"
log = "0.4.7"

[dependencies.hsa-rt-sys]
path = "../hsa-rt-sys"
