[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "hsa-rt"
version = "0.1.0"

[dependencies]
serde = "1.0.19"
serde_derive = "1.0.19"
ndarray = "0.10.12"

[dependencies.hsa-rt-sys]
path = "../hsa-rt-sys"
