[package]
name = "legionella-runtime-nv"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
edition = "2018"

[dependencies]

[dependencies.legionella-runtime-core]
path = "../runtime-core"
