[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "ir"
version = "0.1.0"

[dependencies]
bitflags = "1.0.0"
num-traits = "0.1.37"
serde = "1.0"
serde_derive = "1.0"
rspirv = "0.4.0"
spirv_headers = "1.1.5"

[dependencies.indexvec]
path = "../indexvec"
