[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
name = "legionella-intrinsics"
version = "0.1.0"

[dependencies]
env_logger = "=0.5.12"
log = "=0.4.4"

[dependencies.rustc-intrinsics]
path = "../rustc-intrinsics"
[dependencies.hsa-core]
path = "../hsa-core"