[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
autobins = false
name = "legionella-rustc-driver"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "legionella-bootstrap-rustc"
path = "src/bootstrap-main.rs"

[[bin]]
name = "legionella-rustc"
path = "src/full-main.rs"

[dependencies]
env_logger = "=0.5.12"
log = "=0.4.4"
