[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "hsa-core-gen"
version = "0.1.0"

[dependencies]
quote = "0.3.15"

[dependencies.syn]
version = "0.11.10"
default-features = false
features = ["full", "printing"]

[lib]
proc-macro = true
