[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
name = "fractal"
version = "0.1.0"

[dependencies]
rand = "0.5.5"
tempdir = "*"
geobacter-core = { path = "../../../geobacter-core" }
geobacter-runtime-core = { path = "../../../runtime-core" }
geobacter-vk-std = { path = "../../../vk-std" }
vulkano = "0.11.1"
env_logger = "0.6.0"
log = "0.4.7"
