[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "ndarray"
version = "0.1.0"

[dependencies]
ndarray = "0.10.12"
runtime = { path = "../../runtime" }
env_logger = "0.5.5"

[dependencies.hsa-core]
path = "../../hsa-core"

