[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
build = "src/build.rs"
name = "hsa-rt-sys"
version = "0.1.0"
license = "MIT / Apache-2.0"

[dependencies]

[build-dependencies]
bindgen = "0.49.0"

[lib]
name = "hsa_rt_sys"
path = "src/lib/lib.rs"
