[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
name = "geobacter-vk-std"
version = "0.1.0"

[dependencies]
log = "0.4.7"
geobacter-core = { path = "../geobacter-core" }
geobacter-vk-core = { path = "../vk-core" }
vulkano = "0.11.1"
