[package]
name = "legionella-vk-core"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
edition = "2018"

[dependencies]
vulkano = "0.11.1"
hsa-core = { path = "../hsa-core" }
legionella-shared-defs = { path = "../shared-defs" }
