[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"
license = "MIT / Apache-2.0"
name = "geobacter-vk-intrinsics"
version = "0.1.0"

[dependencies]
num-traits = "0.2.6"
vulkano = "0.11.1"
geobacter-core = { path = "../../geobacter-core" }
geobacter-vk-core = { path = "../../vk-core" }
geobacter-intrinsics-common = { path = "../common" }
geobacter-rustc-help = { path = "../../rustc-help" }
