[package]
name = "examples-amdgpu-fractal"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.6.0"
log = "0.4.7"
ndarray = "0.12.1"
rand = "0.5.5"
lodepng = "2.0.0"
geobacter-core = { path = "../../../geobacter-core" }
geobacter-runtime-core = { path = "../../../runtime-core" }
geobacter-runtime-amd = { path = "../../../runtime-amd" }
geobacter-amdgpu-std = { path = "../../../amdgpu-std" }
hsa-rt = { path = "../../../hsa-rt" }
