[package]
name = "rustc-intrinsics"
version = "0.1.0"
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
license = "MIT / Apache-2.0"
edition = "2018"

[dependencies]
env_logger = "=0.5.12"
log = "=0.4.4"
